# Generated by Django 4.1.1 on 2023-05-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Essaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=28)),
            ],
        ),
    ]
