# Generated by Django 4.1.1 on 2023-05-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptage', '0003_delete_essaie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Essaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=256)),
                ('nb_enfant', models.IntegerField(default=1)),
                ('maried', models.BooleanField(default=False)),
            ],
        ),
    ]
