# Generated by Django 4.1.1 on 2023-05-30 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptage', '0004_essaie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Essaie',
        ),
    ]
